dependencies:
  - name: daemon-fluentd
    version: 0.2.0
    repository: http://atlas.cnct.io
  - name: kafka
    version: 0.2.0
    repository: http://atlas.cnct.io
  - name: central-fluentd
    version: 0.1.0
    repository: http://atlas.cnct.io
  - name: elasticsearch
    version: 0.2.1
    repository: http://atlas.cnct.io
  - name: kibana
    version: 0.1.2
    repository: http://atlas.cnct.io
