apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  ports:
  - name: ldap
    port: 389
    targetPort: 389
  - name: ldap-ssl
    port: 636
    targetPort: 636
  selector:
    app: {{.Release.Name}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name}} 
spec:
  replicas: {{.Values.OpenLdap.Replicas}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
      - name: {{.Release.Name}}
        image: {{.Values.OpenLdap.Image}}:{{.Values.OpenLdap.ImageTag}}
        ports:
          - containerPort: 389
          - containerPort: 636
        env:
        - name: LDAP_DOMAIN
          value: {{.Values.OpenLdap.Domain}}
        - name: LDAP_ADMIN_PASSWORD
          value: {{.Values.OpenLdap.AdminPassword}}
