{{- if .Values.Jenkins.Persistence.Enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.Jenkins.Persistence.StorageClass | quote }}
spec:
  accessModes:
    - {{ .Values.Jenkins.Persistence.AccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.Jenkins.Persistence.Size | quote }}
{{- end }}