apiVersion: v1
kind: Service
metadata:
  name: heapster
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
spec:
  ports:
    - port: 80
      targetPort: {{.Values.heapster_port}}
      nodePort: {{.Values.heapster_nodeport}}
  selector:
    k8s-app: heapster
  type: NodePort
