# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# github, jenkins or ldap
adminEmail: "change me"
adminPassword: "admin"
adminUser: "admin"
javaOptions: "-Xms1024m -Xmx1024m -Djenkins.install.runSetupWizard=false"
jenkinsUrl: "jenkins.cnct.io"
jobsRepo: "change me to repo that has seed job dsl"
kubernetes_cluster: "production-cluster"
storageZone: "us-central-a"
seedJobToken: "seed"

# github, jenkins or ldap
security: "jenkins"
adminUserSalt: "change me if using jenkins security"

slack:
  slackDomain: "samsung-cnct"
  slackRoom: "#ping-jenkins"
  slackApiToken: "change me"

github:
  githubClientId: "change me"
  githubAccessToken: "change me"
  githubUserName: "change me"
  githubClientKey: "change me"
  admin_usernames: "change me"

gke:
  gkeProject: "change me"
  svcAccountId: "change me"
  svcAccountKeyFile:
  svcAccountKey: "change me"

ssh:
  sshPrivateKeyFile:
  sshPrivateKey: "change me"
  sshPublicKeyFile:
  sshPublicKey: "change me"

persistence:
  component: "data_volume"
  enabled: false
  storageClass: "generic"
  accessMode: "ReadWriteOnce"
  size: 8Gi

ldap:
  ldapServer:
  rootDN:
  userSearchBase:
  userSearchFilter: "uid={0}"
  groupMembershipFilter:
  managerDN:
  managerDNPassword: "change me"

agent:
  image: "quay.io/samsung_cnct/k2-ci-jenkins-agent:latest"
  cpu: "200m"
  memory: "1024Mi"
  port: 50000

master:
  image: "quay.io/samsung_cnct/k2-ci-jenkins-master:latest"
  cpu: "200m"
  memory: "1024Mi"
  port: 8080

helm:
  svcAccountId: "change me"
  svcAccountKey: "change me"
  svcAccountKeyFile:
